# Generated by Django 3.2.7 on 2021-10-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('email', models.CharField(max_length=156)),
                ('department', models.CharField(max_length=156)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Valor')),
                ('birth_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
